# -*- coding: utf-8 -*-
"""Div_Recursiva.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OlAf6-vqf1jV6OG8IYiE3sAIxYptgKIU
"""

#division recursiva sin el uso de / // o %

def divRecursiva(dividendo, divisor):
    if dividendo < divisor:
        cociente = 0
    else:
        cociente = 1 + divRecursiva(dividendo - divisor, divisor)
    return cociente

divRecursiva(6,2)