# -*- coding: utf-8 -*-
"""IMC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zogN64_kDpFHGDTNBZpqW9JxJp8ZqF3f
"""

def funcionIMC(peso,altura):
  peso=float(input("Ingrese su peso en kg:"))
  altura=float(input("Ingrese su altura en metros:"))
  imc= peso/altura**2
  print ("Su IMC es:",imc)
  return

funcionIMC(60,172)

