# -*- coding: utf-8 -*-
"""libreria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raM1V_ow9d3R13UJDVzSPtK4Q0gRtTJC
"""

#objetivo
#fecha: 26 de abril de el 2025
#nombre: Jose Gabriel Velasquez Ramos

def funcionSuma(a,b):
  return a+b

def funcionResta(a,b):
  return a-b

def funcionMultiplicacion(a,b):
  return a*b

def funcionDivision(a,b):
  return a/b