# -*- coding: utf-8 -*-
"""Programa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QlRb3ifUaQf57QzE5ZrE7e5CsGIZUHQm
"""

#haciendo uso de la librerias en python se procede a conectar de la siguiente manera

!cp /content/drive/MyDrive/TPtecnicas_de_programacion/Semana6/sabado/libreria/libreria.py /content/

#ahora procederemos a importar el archivo libreria
import libreria

libreria.funcionResta(2,3)